BEGIN TRANSACTION;

CREATE TABLE "android_metadata" ("locale" TEXT DEFAULT 'en_US');
INSERT INTO "android_metadata" VALUES ('en_US');

CREATE TABLE "Word" (
	`_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Word`	TEXT NOT NULL UNIQUE
);
INSERT INTO "Word" ("Word") VALUES 
	("ACCORDING TO HEARSAY"),
	("ACCORDING TO REPORT"),
	("ANNOUNCED"),
	("ALOUD"),
	("AS WE HEAR"),
	("AUDIBLE"),
	("AUDIBLY"),
	("AUDITOR'S"),
	("AUDITIONED"),
	("AURALLY"),
	("BY THE MOUTH"),
	("BY THE SOUND OF IT"),
	("DICTATED"),
	("DISCUSSED"),
	("FOR THE AUDIENCE"),
	("FOR THE AUDITOR"),
	("FOR THE LISTENER"),
	("HEARD"),
	("HEARER'S"),
	("IN AUDITION"),
	("IN CONVERSATION"),
	("IN RECITAL"),
	("IN SPEAKING"),
	("IN SPEECH"),
	("IT IS SAID"),
	("LISTENER'S"),
	("ON THE RADIO"),
	("ORALLY"),
	("OVERHEARD"),
	("PRONOUNCED"),
	("REPORT"),
	("REPORTED"),
	("REPORTEDLY"),
	("SAID"),
	("SAY"),
	("SO IT'S SAID"),
	("SO TO SPEAK"),
	("SO WE HEAR"),
	("SOUND"),
	("SOUNDED"),
	("SOUNDING"),
	("SOUNDS LIKE"),
	("SPEAKER'S"),
	("SPOKEN"),
	("THEY SAY"),
	("TO THE AUDIENCE"),
	("TO THE AUDITOR"),
	("TO THE LISTENER"),
	("VOCAL"),
	("VOICED"),
	("WE HEAR"),
	("WHEN HEARD");
	

COMMIT;
